name: Testes Mobile no Sauce Labs 🌶️

on:
  push:
    branches: [ "main" ]

jobs:
  testar-na-nuvem:
    runs-on: ubuntu-latest 

    steps:
      - name: 🛎️ Clonar o código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Instalar dependências
        working-directory: ./projects-javascript/yodapp-robot
        run: npm install

      - name: 🚀 Subir o APK pro Cofre do Sauce Labs
        run: |
          curl -u "${{ secrets.SAUCE_USERNAME }}:${{ secrets.SAUCE_ACCESS_KEY }}" \
          --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form 'payload=@"projects/yodapp-robot/app/yodapp-beta.apk"' \
          --form 'name="yodapp-beta.apk"'

      - name: 🧪 Rodar os testes no celular de verdade!
        working-directory: ./projects-javascript/yodapp-robot
        # Passando as chaves pro código WDIO conseguir ler
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test