name: Yodapp CI Raiz 🤖

on:
  push:
    branches: [ "main" ]

jobs:
  testar-no-emulador:
    # AQUI ESTÁ A SALVAÇÃO: macos-13 é o Mac com processador Intel!
    runs-on: macos-13 

    steps:
      - name: 🛎️ Clonar o código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Instalar dependências do Yodapp
        working-directory: ./projects-javascript/yodapp-robot
        run: npm install

      - name: 📱 Subir Emulador e Rodar Testes
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          # Voltamos pro x86_64 (Intel), que funciona no macos-13
          arch: x86_64
          target: default
          profile: Nexus 6
          disable-animations: true
          working-directory: ./projects-javascript/yodapp-robot
          script: npm run test